robot: go2 # turtlebot | go2 | nimrod

frames:
  odom_frame: odom
  # base_frame: base_footprint

  base_frame: base_link
  # base_frame: zedm_left_camera_frame

model: 
  model_name: pilot_bsz128_c1_ac1_gcp0.2_mdp0.0_ph16_2024-10-09_20-26-18

# pilot_bsz64_c10_ac2_gcp0.2_mdp0.0_ph32_2024-10-10_15-46-25
# pilot_bsz64_c5_ac2_gcp0.2_mdp0.0_ph32_2024-10-10_13-14-24
# pilot_bsz128_c1_ac1_gcp0.2_mdp0.0_ph16_2024-10-09_20-26-18
# pilot_bsz128_c10_ac2_gcp0.2_mdp0.0_ph16_2024-10-10_00-48-22

  model_version: best_model # best_model | latest | <epoch_number> (int)

  frame_rate: 12 # NOTE: please pay atteniton that this value is similar to the sampling rate
                # of the data collected to train the policy
  pub_rate: 10
  inference_rate: 2
  wpt_i: 8

topics: 
  image_topic: /zedm/zed_node/depth/depth_registered
  # image_topic: /zedm/zed_node/rgb/image_rect_color
  obj_det_topic: /obj_detect_publisher_node/object
  odom_topic: /zedm/zed_node/odom

filter:

  sensor_moving_window_size: 1
  smoothen_time: 0.1

  kalman:
    enable: False
    k_B: 0.03
    sensor_variance: [1e-1,1e-1,1e-1]
    moving_window_size: 15
    alpha: 200
    error_threshold: 0.6




