robot: go2 # turtlebot | go2 | nimrod

frames:
  odom_frame: odom
  base_frame: base_link

model: 
  # model_name: pilot-go-to-the-pic-pidiff_2024-06-25_09-43-16
  model_name: pilot_tracking-bsz128_c3_ac3_td2_2024-08-06_21-35-26
  model_version: latest # best_model | latest | <epoch_number> (int)
  # model_name: pilot-turtle-static-follower_2024-07-03_00-16-16

  frame_rate: 7 # NOTE: please pay atteniton that this value is similar to the sampling rate
                # of the data collected to train the policy
  inference_rate: 5
  wpt_i: 2

topics: 
  image_topic: /zedm/zed_node/depth/depth_registered
  # image_topic: /zedm/zed_node/rgb/image_rect_color
  obj_det_topic: /obj_detect_publisher_node/object
  odom_topic: /zedm/zed_node/odom

