robot: go2 # turtlebot | go2 | nimrod

frames:
  odom_frame: odom
  # base_frame: base_footprint

  base_frame: base_link
  # base_frame: zedm_left_camera_frame

model: 

  # simple bc

  # c5
  # model_name: cnn_mlp_bsz128_c3_ac2_gcFalse_gcp0.3_ph5_tceTrue_ntmaxmin_2024-11-12_16-33-56

  # ViNT
  # model_name: vint_bsz128_c3_ac2_gcTrue_gcp0.3_ph5_tceTrue_ntmaxmin_2024-11-12_17-48-53

  # Pidiff

  # outside & zero shot inside:
  # model_name: pidiff_bsz128_c2_ac1_gcTrue_gcp0.0_ah16_ph32_tceTrue_ntmaxmin_2024-11-21_11-26-41
  # model_name: pidiff_bsz128_c2_ac1_gcTrue_gcp0.75_ah16_ph32_tceTrue_ntmaxmin_2024-11-21_11-56-45 # zero shot 
  model_name: pidiff_bsz256_c2_ac2_gcTrue_gcp0.75_ah16_ph32_tceTrue_ntmaxmin_2024-11-24_17-17-18
  # indoor 0.5 data:
  # model_name: pidiff_bsz128_c2_ac1_gcTrue_gcp0.0_ah16_ph32_tceTrue_ntmaxmin_2024-11-21_11-26-41_fintuned_2024-11-21_18-40-44_p50
  # model_name: pidiff_bsz128_c2_ac1_gcTrue_gcp0.75_ah16_ph32_tceTrue_ntmaxmin_2024-11-21_11-56-45_fintuned_2024-11-21_18-46-57_p50

  # indoor full data:
  # model_name: pidiff_bsz128_c2_ac1_gcTrue_gcp0.0_ah16_ph32_tceTrue_ntmaxmin_2024-11-21_11-26-41_fintuned_2024-11-21_13-37-36
  # model_name: pidiff_bsz128_c2_ac1_gcTrue_gcp0.75_ah16_ph32_tceTrue_ntmaxmin_2024-11-21_11-56-45_fintuned_2024-11-21_13-51-09


  model_version: latest # best_model | latest | <epoch_number> (int)

  frame_rate: 15 # NOTE: please pay atteniton that this value is similar to the sampling rate
                # of the data collected to train the policy

  inference_rate: 10

  # # Vint 
  # pub_rate: 5
  # inference_rate: 10

  # # SimpleBC 
  # pub_rate: 5
  # inference_rate: 15

  wpt_i: 4
  use_subgoal: True

topics: 
  image_topic: /zedm/zed_node/depth/depth_registered
  # image_topic: /zedm/zed_node/rgb/image_rect_color
  obj_det_topic: /obj_detect_publisher_node/object
  odom_topic: /zedm/zed_node/odom

filter:

  sensor_moving_window_size: 10
  smoothen_time: 0.2





