robot: go2 # turtlebot | go2 | nimrod

frames:
  odom_frame: odom
  base_frame: base_footprint

  # base_frame: base_link
  # base_frame: zedm_left_camera_frame

model: 
  # model_name: pilot-go-to-the-pic-pidiff_2024-06-25_09-43-16
  model_name: pilot_bsz128_c4_ac3_gcp0.5_mdp0.25_ph_82024-08-19_18-10-30
  model_version: latest # best_model | latest | <epoch_number> (int)
  # model_name: pilot-turtle-static-follower_2024-07-03_00-16-16

  frame_rate: 7 # NOTE: please pay atteniton that this value is similar to the sampling rate
                # of the data collected to train the policy
  inference_rate: 3
  wpt_i: 2

topics: 
  image_topic: /zedm/zed_node/depth/depth_registered
  # image_topic: /zedm/zed_node/rgb/image_rect_color
  obj_det_topic: /obj_detect_publisher_node/object
  odom_topic: /zedm/zed_node/odom

filter:

  sensor_moving_window_size: 5
  
  kalman:
    enable: True
    k_B: 0.03
    sensor_variance: [1e-1,1e-1,1e-1]
    moving_window_size: 15
    alpha: 200
    error_threshold: 0.6




