robot: go2 # turtlebot | go2 | nimrod

frames:
  odom_frame: odom
  # base_frame: base_footprint

  base_frame: base_link
  # base_frame: zedm_left_camera_frame

model: 
  
  # simple bc
  # c1
  # model_name: cnn_mlp_bsz80_c1_ac1_gcFalse_gcp0.1_ph16_tceTrue_ntmaxmin_2024-11-03_18-20-19
  # c5
  # model_name: cnn_mlp_bsz80_c5_ac5_gcFalse_gcp0.1_ph16_tceTrue_ntmaxmin_2024-11-05_23-45-29

  # ViNT
  # c1
  # model_name: vint_bsz80_c1_ac1_gcTrue_gcp0.1_ph16_tceTrue_ntmaxmin_2024-11-03_19-10-55
  # c5
  # model_name: vint_bsz80_c5_ac5_gcTrue_gcp0.1_ph16_tceTrue_ntmaxmin_2024-11-06_01-00-47

  # Pidiff
  # c1 gc0.1
  # model_name: pidiff_bsz80_c1_ac1_gcTrue_gcp0.1_ph32_tceTrue_ntmaxmin_dnsddpm_2024-11-04_20-40-12

  # c1 gc0.5
  model_name: pidiff_bsz80_c1_ac1_gcTrue_gcp0.5_ph32_tceTrue_ntmaxmin_dnsddpm_2024-11-05_18-02-57

  # w/o target and goal
  # model_name: pidiff_bsz80_c1_ac1_gcFalse_gcp0.1_ph32_tceFalse_ntmaxmin_dnsddpm_2024-11-06_07-47-23

  model_version: latest # best_model | latest | <epoch_number> (int)

  frame_rate: 12 # NOTE: please pay atteniton that this value is similar to the sampling rate
                # of the data collected to train the policy
  pub_rate: 4
  inference_rate: 4
  wpt_i: 8
  use_subgoal: True

topics: 
  image_topic: /zedm/zed_node/depth/depth_registered
  # image_topic: /zedm/zed_node/rgb/image_rect_color
  obj_det_topic: /obj_detect_publisher_node/object
  odom_topic: /zedm/zed_node/odom

filter:

  sensor_moving_window_size: 1
  smoothen_time: 0.0

  kalman:
    enable: False
    k_B: 0.03
    sensor_variance: [1e-1,1e-1,1e-1]
    moving_window_size: 15
    alpha: 200
    error_threshold: 0.6




