
# ROS topics
topics:
  odom_topic: /turtlebot/odom
  goal_topic: /goal_pose
  cmd_topic: /turtlebot/cmd_vel

# Control
control:
  rotate_dist_threshold: 0.1 # [m]
  linear:
    max_vel: 0.22 # change depend on robot config
    min_vel: -0.1
    kp: 0.35
    ki: 0.001
    kd: 0.001

  angular:
    max_vel: 1.8
    min_vel: -1.8
    kp: 0.2
    ki: 0.001
    kd: 0.001
