
# ROS topics
topics:
  # odom_topic: /turtlebot/odom
  odom_topic: /zedm/zed_node/odom
  # goal_topic: /goal_pose_model
  goal_topic: /goal_pose_filtered
  cmd_topic: /wfc/cmd_vel

# Control
control:
  rotate_dist_threshold: 0.1 # [m]
  linear:
    max_vel: 2. # change depend on robot config
    min_vel: -1.
    kp: 0.1
    ki: 0.0
    kd: 0.0

  angular:
    max_vel: 1.
    min_vel: -1.
    kp: 0.1
    ki: 0.0
    kd: 0.0

  smoothing:
    k: 0.2  # Coefficient for current command influence
    e: 0.1  # Coefficient for previous raw command influence
